package com.charliesbot.shared.core.domain.platform

interface StringProvider {
  fun getString(key: StringKey): String
}

enum class StringKey {
  SETTINGS_EXPORT_SUCCESS,
  SETTINGS_EXPORT_ERROR,
  SETTINGS_SYNC_SUCCESS,
  SETTINGS_SYNC_ERROR,
  SETTINGS_VERSION_COPIED,
  NOTIFICATION_ONE_HOUR_TITLE,
  NOTIFICATION_ONE_HOUR_MESSAGE,
  NOTIFICATION_COMPLETION_TITLE,
  NOTIFICATION_COMPLETION_MESSAGE,
  NOTIFICATION_SMART_REMINDER_1H_TITLE,
  NOTIFICATION_SMART_REMINDER_1H_MESSAGE,
  NOTIFICATION_SMART_REMINDER_START_TITLE,
  NOTIFICATION_SMART_REMINDER_START_MESSAGE,
}
